"""Wan-Fun Control-Camera용 궤도 카메라 파일 (RealEstate10K/CameraCtrl 형식) 만들기.

형식: 첫 줄은 버려짐(헤더), 이후 프레임마다
    timestamp fx fy cx cy 0 0 w2c(3x4, 행 우선)
fx, fy, cx, cy는 정규화 값. VideoX-Fun의 process_pose_file은 원래 1280x720 기준으로 fx를 가로세로 비율만큼
다시 늘리므로 (정사각 출력이면 fx *= 1280/720), 원하는 정규화 초점거리를 그만큼 나눠서 적는다.

카메라: OpenCV 좌표 (x 오른쪽, y 아래, z 앞). 물체 중심 = 첫 카메라 앞 d 지점.
프레임 k의 카메라 = 물체 중심을 축으로 y축 회전 (수평 궤도), 선택적으로 고도 변화.

사용법:
    python scripts/make_orbit_pose.py --out build/orbit_360.txt --frames 81 --degrees 360 --dist 1.5 --fov 50
"""
import argparse

import numpy as np


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--frames", type=int, default=81)
    ap.add_argument("--degrees", type=float, default=360.0)
    ap.add_argument("--dist", type=float, default=1.5, help="첫 카메라에서 물체 중심까지 거리 (장면 단위)")
    ap.add_argument("--fov", type=float, default=50.0, help="가로 화각 (도)")
    ap.add_argument("--elev", type=float, default=0.0, help="궤도 도중 최대 고도 변화 (도, 사인 곡선)")
    ap.add_argument("--aspect", type=float, default=1.0, help="출력 가로/세로 비")
    ap.add_argument("--waypoints", default=None,
                    help="'이름:방위각:고도,...' 순서로 지나가는 궤도 (각도 거리에 비례해 프레임 배분). 첫 점은 입력 카메라 (0:0)")
    args = ap.parse_args()

    f_n = 0.5 / np.tan(np.radians(args.fov) / 2)          # 정규화 초점거리 (가로 기준)
    pose_ratio = 1280 / 720
    fx_write = f_n / (pose_ratio / args.aspect) if pose_ratio > args.aspect else f_n
    fy_write = f_n * args.aspect                           # 세로 기준 정규화
    p = np.array([0.0, 0.0, args.dist])
    lines = ["# orbit around object center, generated by make_orbit_pose.py"]
    # 프레임별 (방위각, 고도) 목록. 고도 양수 = 물체 위에서 내려다봄.
    marks = {}
    if args.waypoints:
        wps = [(w.split(":")[0], float(w.split(":")[1]), float(w.split(":")[2])) for w in args.waypoints.split(",")]
        seg = [np.hypot(b[1] - a[1], b[2] - a[2]) for a, b in zip(wps[:-1], wps[1:])]
        cum = np.concatenate([[0], np.cumsum(seg)]) / sum(seg) * (args.frames - 1)
        ts = np.arange(args.frames)
        azs = np.interp(ts, cum, [w[1] for w in wps])
        els = np.interp(ts, cum, [w[2] for w in wps])
        marks = {w[0]: int(round(c)) for w, c in zip(wps, cum)}
    else:
        tt = np.linspace(0, 1, args.frames)
        azs = args.degrees * tt
        els = args.elev * np.sin(2 * np.pi * tt)
    frames_meta = []
    for k in range(args.frames):
        yaw = np.radians(azs[k])
        el = -np.radians(els[k])                           # OpenCV y가 아래라서 부호 반전 (양수 = 위에서 봄)
        Ry = np.array([[np.cos(yaw), 0, np.sin(yaw)], [0, 1, 0], [-np.sin(yaw), 0, np.cos(yaw)]])
        Rx = np.array([[1, 0, 0], [0, np.cos(el), -np.sin(el)], [0, np.sin(el), np.cos(el)]])
        R = Ry @ Rx
        c2w = np.eye(4)
        c2w[:3, :3] = R
        c2w[:3, 3] = p - R @ p                             # 물체 중심 고정
        w2c = np.linalg.inv(c2w)[:3]
        vals = [k, fx_write, fy_write, 0.5, 0.5, 0, 0] + w2c.reshape(-1).tolist()
        lines.append(" ".join(f"{v:.9g}" for v in vals))
        frames_meta.append({"frame": k, "azimuth": float(azs[k]), "elevation": float(els[k]), "c2w_opencv": c2w.tolist()})
    open(args.out, "w").write("\n".join(lines) + "\n")
    import json
    json.dump({"fov_x_deg": args.fov, "dist": args.dist, "marks": marks, "frames": frames_meta},
              open(args.out.rsplit(".", 1)[0] + ".json", "w"), indent=1)
    print(f"{args.frames} poses -> {args.out}", marks)


if __name__ == "__main__":
    main()
